<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>list</string>
		<string>todo</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>List</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.text</string>
				</dict>
			</dict>
			<key>match</key>
			<string>.*(https?://\S+).*</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*[-_]{3,}\s*\n</string>
			<key>name</key>
			<string>comment.line.divider</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::.*::</string>
			<key>name</key>
			<string>entity.name.section</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.header</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.note</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^:]+):(.*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*-</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>string.quoted.hyphen.untitled</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.klist</string>
	<key>uuid</key>
	<string>0AC2E574-B1AB-40D5-A2AD-A03085B0DAE8</string>
</dict>
</plist>
